// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/calendar/Calendar.vue')['default']
    CalendarButton: typeof import('./src/components/calendar/CalendarButton.vue')['default']
    CalendarCalendar: typeof import('./src/components/calendar/CalendarCalendar.vue')['default']
    CalendarComponents: typeof import('./src/components/calendar/CalendarComponents.vue')['default']
    CalendarHeader: typeof import('./src/components/calendar/CalendarHeader.vue')['default']
    CalendarMonth: typeof import('./src/components/calendar/CalendarMonth.vue')['default']
    CalendarMonthUnit: typeof import('./src/components/calendar/CalendarMonthUnit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectHome: typeof import('./src/components/home/ProjectHome.vue')['default']
    ProjectHomeCalendar: typeof import('./src/components/home/ProjectHomeCalendar.vue')['default']
  }
}
